In [1]:
import numpy as np

In [2]:
# Задание 1
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])


In [3]:
mean_a = np.mean(a,axis = 0)
mean_a

array([2. , 8.4])

In [4]:
# Задание 2
a_centred = np.subtract(a,mean_a)
a_centred

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [5]:
# Задание 3
a_centred_sp = np.prod(a_centred, axis = 1).sum()


In [6]:
a_centred_sp = a_centred_sp / (a.shape[0] - 1)
a_centred_sp

2.0

In [7]:
# Задание 4
b = np.cov(a.transpose())
b


array([[1. , 2. ],
       [2. , 4.3]])

In [8]:
b[0,1]

2.0